front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Front:index }
front_login:
    path:     /login
    defaults:  { _controller: FrontBundle:Security:login }
front_register:
    path:     /register
    defaults:  { _controller: FrontBundle:Security:register }
front_logout:
   path:      /logout
front_user_profile:
    path:     /users/{fullName}/{userId}
    defaults:  { _controller: FrontBundle:User:profile }
front_post_show:
    path:     /picture
    defaults:  { _controller: FrontBundle:Post:show }