front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Front:index }
front_login:
    path:     /login
    defaults:  { _controller: FrontBundle:Security:login }
front_logout:
   path: /logout