# SECURITY ROUTING #
front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Front:index }
front_login:
    path:     /login
    defaults:  { _controller: FrontBundle:Security:login }
front_register:
    path:     /register
    defaults:  { _controller: FrontBundle:Security:register }
front_logout:
   path:      /logout
# USER ROUTING #
front_user_profile:
    path:     /users/{fullName}/{userId}
    defaults:  { _controller: FrontBundle:User:profile }
# POST ROUTING #
front_post_show:
    path:     /pictures/{postId}
    defaults:  { _controller: FrontBundle:Post:show }
front_post_add:
    path:     /pictures/add
    defaults:  { _controller: FrontBundle:Post:add }
