api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /admin

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /