back_index:
    path:     /
    defaults: { _controller: BackBundle:Back:index }
back_user_invite_index:
    path:     /invitations
    defaults: { _controller: BackBundle:UserInvite:index }
back_user_invite_add:
    path:     /invitations/add
    defaults: { _controller: BackBundle:UserInvite:add }